server:
  port: 8989
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848   # nacos地址
    gateway:
      routes:
        - id: OD-service
          uri: lb://onlineDoctor
          predicates:
            - Path=/**
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: user-doctor-service
          uri: lb://userDoctor
          predicates:
            - Path=/doctor/**
        - id: order-service
          uri: lb://order
          predicates:
            - Path=/**


      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true