server:
  # 端口
  port: 8089
  tomcat:
    max-http-form-post-size: -1

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 7200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# DataSourceProperties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduate_project?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lgh1906200123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size:  15
      minimum-idle: 5
      idle-timeout: 30000
  application:
    name: userPatient
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    mongodb:
      uri: mongodb://localhost/Users
  redis:
    host: 114.116.113.91
    port: 6379
    password: lghredis
    timeout: 3000




# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lgh.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
